export const FOOD_DATA = {
  breakfast: {
    'Oats': { calories: 150, protein: 5, carbs: 27, fat: 3, category: 'healthy' },
    'Boiled Eggs': { calories: 155, protein: 13, carbs: 1, fat: 11, category: 'healthy' },
    'Fruits': { calories: 95, protein: 1, carbs: 25, fat: 0, category: 'healthy' },
    'Idli': { calories: 120, protein: 4, carbs: 25, fat: 1, category: 'healthy' },
    'Dosa': { calories: 180, protein: 5, carbs: 30, fat: 3, category: 'healthy' },
    'Upma': { calories: 160, protein: 5, carbs: 28, fat: 3, category: 'healthy' },
    'WW Bread + PB': { calories: 250, protein: 10, carbs: 22, fat: 14, category: 'healthy' },
    'Smoothie': { calories: 210, protein: 8, carbs: 35, fat: 4, category: 'healthy' },
    'Jam Bread': { calories: 260, protein: 4, carbs: 55, fat: 3, category: 'junk' },
    'Sugary Cereals': { calories: 300, protein: 3, carbs: 65, fat: 2, category: 'junk' },
    'Donuts': { calories: 350, protein: 4, carbs: 45, fat: 18, category: 'junk' },
    'Pancakes': { calories: 450, protein: 8, carbs: 80, fat: 12, category: 'junk' },
    'Fried Paratha': { calories: 350, protein: 6, carbs: 45, fat: 16, category: 'junk' },
    'Packaged Juice': { calories: 150, protein: 1, carbs: 35, fat: 0, category: 'junk' },
    'Manual Entry': { calories: 0, protein: 0, carbs: 0, fat: 0, category: 'healthy' }
  },
  lunch: {
    'Rice + Dal': { calories: 350, protein: 12, carbs: 65, fat: 5, category: 'healthy' },
    'Chapati + Veg': { calories: 300, protein: 10, carbs: 45, fat: 8, category: 'healthy' },
    'Rice + Chicken': { calories: 450, protein: 35, carbs: 55, fat: 12, category: 'healthy' },
    'Chicken Salad': { calories: 300, protein: 30, carbs: 10, fat: 12, category: 'healthy' },
    'Curd Rice': { calories: 250, protein: 6, carbs: 40, fat: 8, category: 'healthy' },
    'Veg Khichdi': { calories: 280, protein: 8, carbs: 50, fat: 6, category: 'healthy' },
    'Paneer + Roti': { calories: 420, protein: 22, carbs: 40, fat: 18, category: 'healthy' },
    'Fried Rice': { calories: 550, protein: 12, carbs: 80, fat: 22, category: 'junk' },
    'Noodles': { calories: 480, protein: 10, carbs: 70, fat: 18, category: 'junk' },
    'Burger': { calories: 600, protein: 25, carbs: 50, fat: 35, category: 'junk' },
    'Pizza Slice': { calories: 280, protein: 12, carbs: 35, fat: 12, category: 'junk' },
    'Shawarma': { calories: 550, protein: 30, carbs: 40, fat: 32, category: 'junk' },
    'Heavy Biryani': { calories: 750, protein: 35, carbs: 85, fat: 35, category: 'junk' },
    'Manual Entry': { calories: 0, protein: 0, carbs: 0, fat: 0, category: 'healthy' }
  },
  dinner: {
    'Chapati + Sabzi': { calories: 250, protein: 8, carbs: 35, fat: 8, category: 'healthy' },
    'Soup + Salad': { calories: 180, protein: 6, carbs: 20, fat: 8, category: 'healthy' },
    'Grilled Fish': { calories: 250, protein: 25, carbs: 0, fat: 15, category: 'healthy' },
    'Paneer + Veg': { calories: 350, protein: 20, carbs: 15, fat: 22, category: 'healthy' },
    'Light Rice/Dal': { calories: 280, protein: 10, carbs: 45, fat: 6, category: 'healthy' },
    'Omelette/Salad': { calories: 220, protein: 18, carbs: 8, fat: 14, category: 'healthy' },
    'Late Pizza': { calories: 700, protein: 30, carbs: 85, fat: 32, category: 'junk' },
    'Fried Chicken': { calories: 600, protein: 40, carbs: 30, fat: 40, category: 'junk' },
    'Instant Noodles': { calories: 380, protein: 8, carbs: 55, fat: 15, category: 'junk' },
    'Heavy Biryani': { calories: 850, protein: 40, carbs: 95, fat: 42, category: 'junk' },
    'Fast Food Combo': { calories: 950, protein: 35, carbs: 110, fat: 48, category: 'junk' },
    'Manual Entry': { calories: 0, protein: 0, carbs: 0, fat: 0, category: 'healthy' }
  },
  snack: {
    'Nuts': { calories: 160, protein: 6, carbs: 6, fat: 14, category: 'healthy' },
    'Fruit Snack': { calories: 95, protein: 1, carbs: 25, fat: 0, category: 'healthy' },
    'Boiled Corn': { calories: 120, protein: 4, carbs: 25, fat: 2, category: 'healthy' },
    'Sprouts': { calories: 100, protein: 8, carbs: 18, fat: 1, category: 'healthy' },
    'Yogurt': { calories: 100, protein: 10, carbs: 8, fat: 3, category: 'healthy' },
    'Protein Bar': { calories: 210, protein: 20, carbs: 22, fat: 6, category: 'healthy' },
    'Chips': { calories: 150, protein: 2, carbs: 15, fat: 10, category: 'junk' },
    'Chocolate': { calories: 210, protein: 3, carbs: 25, fat: 12, category: 'junk' },
    'Ice Cream': { calories: 250, protein: 4, carbs: 30, fat: 14, category: 'junk' },
    'Soft Drink': { calories: 150, protein: 0, carbs: 40, fat: 0, category: 'junk' },
    'Biscuits': { calories: 180, protein: 2, carbs: 28, fat: 7, category: 'junk' },
    'Fries': { calories: 350, protein: 4, carbs: 45, fat: 18, category: 'junk' },
    'Manual Entry': { calories: 0, protein: 0, carbs: 0, fat: 0, category: 'healthy' }
  }
};
